version: '3'

services:
  cq-frontend-build:
    container_name: cq-frontend-build
    build:
      context: .
      dockerfile: build.Dockerfile
    image: cq-frontend-build:v1

  cq-frontend-dev:
    container_name: cq-frontend-dev
    image: node:latest
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5173:5173"
    command: "sh -c 'npm install && npm run dev -- --host'"