POST {{host}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "{{username}}",
  "password": "{{password}}"
}

> {% client.global.set("token", response.body.token) %}

####
POST {{host}}/questions
Accept: application/json
Authorization: {{token}}

{
  "id": null,
  "question": "What is the topping of a Hawaii pizza?",
  "version": 0
}

> {% client.global.set("question_id", response.body.id) %}

####
POST {{host}}/questions
Accept: application/json
Authorization: {{token}}

{
  "id": null,
  "rating": 0,
  "question_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "user_id": null,
  "version": 0
}